export default {
  content:[
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'], // Use Plus Jakarta Sans for Display
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#ccdbf3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "on-surface": "#0d1c2e",
        "on-surface-variant": "#434655",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        "primary": "#004ac6",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "secondary": "#006c49",
        "on-secondary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        "tertiary": "#ad0033",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d22348",
        "on-tertiary-container": "#ffecec",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffdadb",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-tertiary-fixed": "#40000d",
        "on-tertiary-fixed-variant": "#92002a",
        "on-background": "#0d1c2e",
        "surface-variant": "#d5e3fc"
      }
    },
  },
   plugins:[
    require('@tailwindcss/typography'), 
  ],
}